# Generated by Django 4.2 on 2023-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_ar', models.CharField(max_length=1000)),
                ('version_fra', models.CharField(max_length=1000)),
                ('populaire', models.BooleanField(default=False)),
                ('explication', models.CharField(max_length=1000)),
                ('nom', models.CharField(default='test', max_length=100)),
            ],
        ),
    ]
