# Generated by Django 4.2 on 2023-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverbe',
            name='populaire',
            field=models.BooleanField(default=False),
        ),
    ]
