# Generated by Django 4.2 on 2023-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbe', '0002_proverbe_populaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='proverbe',
            name='nom',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
